-- MySQL Script generated by MySQL Workbench
-- Tue Sep 24 15:26:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wemanity
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wemanity
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wemanity` DEFAULT CHARACTER SET utf8 ;
USE `wemanity` ;

-- -----------------------------------------------------
-- Table `wemanity`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wemanity`.`city` ;

CREATE TABLE IF NOT EXISTS `wemanity`.`city` (
  `id` INT NOT NULL,
  `department` VARCHAR(3) NULL,
  `name` VARCHAR(45) NULL,
  `zipcode` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wemanity`.`cinema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wemanity`.`cinema` ;

CREATE TABLE IF NOT EXISTS `wemanity`.`cinema` (
  `id` INT NOT NULL,
  `street` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cinema_city_idx` (`city_id` ASC),
  CONSTRAINT `fk_cinema_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `wemanity`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wemanity`.`movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wemanity`.`movie` ;

CREATE TABLE IF NOT EXISTS `wemanity`.`movie` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `start` DATETIME NULL,
  `end` DATETIME NULL,
  `cinema_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movie_cinema1_idx` (`cinema_id` ASC),
  CONSTRAINT `fk_movie_cinema1`
    FOREIGN KEY (`cinema_id`)
    REFERENCES `wemanity`.`cinema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
